version: '3.8'

services:
  serving:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.serving
    container_name: prediction_service
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
      - MODEL_URI=models:/Telco-Churn-Prediction/latest
      - SCALER_PATH=/app/data/processed/scaler.joblib
    volumes:
      - ../../data:/app/data
    networks:
      - mlflow-net
    restart: always

networks:
  mlflow-net:
    external: true
    name: mlflow-net
