name: Train Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'infrastructure/**'
      - 'data/**'
  workflow_dispatch:

jobs:
  train-pipeline:
    name: Run Training Pipeline
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Run Training Pipeline
        run: |
          chmod +x ./run_pipeline.sh
          ./run_pipeline.sh

      
      - name: Set Image Tag
        id: vars
        run: echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          IMG: ${{ secrets.DOCKERHUB_USERNAME }}/mlopstelcoserving
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          echo "Building image with tag: $TAG"
          docker build -f docker/Dockerfile.serving -t $IMG:$TAG -t $IMG:latest .
          docker push $IMG:$TAG
          docker push $IMG:latest

      - name: Update Values and Deploy to K8s
        env:
          TAG: ${{ steps.vars.outputs.tag }}
        run: |
          # Update tag locally for Helm execution
          sed -i "s/tag: .*/tag: \"$TAG\"/" infrastructure/servingChart/values.yaml
          
          # Deploy using Helm
          helm upgrade --install serving-service ./infrastructure/servingChart -n serving --create-namespace

      - name: Verify Deployment Status
        run: |
          echo "Waiting for pods to be ready..."
          kubectl rollout status deployment/serving-service-serving-chart --timeout=120s
